---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pv-claim
  labels:
    app: ghost
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: inlets-ghost-demo
spec:
  containers:
  - name: ghost
    image: docker.io/library/ghost:5.59.0-alpine
    env:
    - name: url
      value: https://< FQDN Based on the parameters passed to terraform >
    - name: NODE_ENV
      value: development
    volumeMounts:
    - name: ghost-persistent-storage
      mountPath: /var/lib/ghost/content
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  - name: inlets
    image: ghcr.io/inlets/inlets-pro:0.9.20
    args:
    - "http"
    - "client"
    - "--url=wss://< Public IP Address of EC2 instance >:8123"
    - "--token-file=/var/secrets/inlets-server-token/inlets-server-token"
    - "--license-file=/var/secrets/inlets-license/inlets-license"
    - "--upstream=http://127.0.0.1:2368"
    volumeMounts:
    - mountPath: /var/secrets/inlets-server-token
      name: inlets-server-token
    - mountPath: /var/secrets/inlets-license
      name: inlets-license
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  volumes:
  - name: ghost-persistent-storage
    persistentVolumeClaim:
      claimName: ghost-pv-claim
  - name: inlets-license
    secret:
      secretName: inlets-license
  - name: inlets-server-token
    secret:
      secretName: inlets-server-token
