- name: Preflight tasks
  hosts: all
  become: false
  vars:
    default_inlets_version : 0.9.20
  run_once: true
  tasks:
  - name: Generate inlets server token
    no_log: true
    ansible.builtin.set_fact:
      inlets_token: "{{ lookup('community.general.random_string', special=false, length=64) }}"
  - name: Set inlets version if not set
    ansible.builtin.set_fact:
      inlets_version: "{{ default_inlets_version }}"
    when: inlets_version | default('') | length == 0

- name: Install Inlets Server
  hosts: inlets_server
  become: true
  roles:
  - common
  - inlets-server

- name: Install Inlets Client
  hosts: inlets_client
  become: true
  roles:
  - common
  - inlets-client
