- name: Generate facts
  hosts: all
  become: false
  tasks:
  - name: Generate inlets server token
    delegate_to: localhost
    run_once: true
    no_log: true
    ansible.builtin.set_fact:
      inlets_token: "{{ lookup('community.general.random_string', special=false, length=64) }}"

- name: Install Inlets Server
  hosts: inlets-server
  become: true
  roles:
  - common
  - inlets-server

- name: Install Inlets Client
  hosts: inlets-server
  become: true
  roles:
  - common
  - inlets-client
